package com.cuongphan.bugrap.designs_views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends VerticalLayout {
    protected ComboBox<org.vaadin.bugrap.domain.entities.Project> projectComboBox;
    protected Label userName;
    protected Label logoutLabel;
    protected Label bugLabel;
    protected Label requestAFeature;
    protected Label manageLabel;
    protected Label projectCountLable;
    protected HorizontalLayout searchBoxLayout;
    protected NativeSelect<org.vaadin.bugrap.domain.entities.ProjectVersion> versionNS;
    protected HorizontalLayout filterLayout;
    protected HorizontalLayout assigneeLayout;
    protected Label assigneeLabel;
    protected MenuBar assigneeMB;
    protected HorizontalLayout statusLayout;
    protected Label statusLabel;
    protected MenuBar statusMB;
    protected Grid<org.vaadin.bugrap.domain.entities.Report> reportGrid;

    public MainDesign() {
        Design.read(this);
    }
}
