package com.cuongphan.bugrap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BugrapApp extends CssLayout {
    protected Image profileIcon;
    protected Label profileNameLabel;
    protected Image logoutIcon;
    protected Label logoutLabel;
    protected Image bugIcon;
    protected Label bugLabel;
    protected Image requestIcon;
    protected Label requestLabel;
    protected Image manageIcon;
    protected Label manageLabel;
    protected Label projectCountLable;
    protected TextField searchBar;

    public BugrapApp() {
        Design.read(this);
    }
}
